Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace PieShop.Controllers;

public class ContactController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using PieShop.Models;
using PieShop.Models.Repositories;
using PieShop.ViewModels;

namespace PieShop.Controllers;

public class PieController : Controller
{
    private readonly IPieRepository _pieRepo;
    private readonly ICategoryRepository _categoryRepo;
    
    public PieController(IPieRepository pieRepo, ICategoryRepository categoryRepo)
    {
        _pieRepo = pieRepo;
        _categoryRepo = categoryRepo;
    }
    // public IActionResult List()
    // {
    //     var pies = _pieRepo.GetPies();
    //     var pieListViewModel = new PieListViewModel(pies, "Cheese Cake");
    //
    //     return View(pieListViewModel);
    // }
    
    public IActionResult List(string category)
    {
        IEnumerable<Pie> pies;
        string? currentCategoryName;
      
        if (string.IsNullOrEmpty(category))
        {
            pies = _pieRepo.GetPies().OrderBy(p => p.PieId);
            currentCategoryName = "All pies";
        }
        else
        {
            var currentCategory =
                _categoryRepo.GetCategories().FirstOrDefault(c => c.CategoryName == category);
            pies = _pieRepo.GetPies().Where(p => p.Category == currentCategory?.CategoryId);
            currentCategoryName = currentCategory?.CategoryName ?? "All pies";
        }
    
        return View(new PieListViewModel(pies, currentCategoryName));
    }
    
    public IActionResult Details(int id)
    {
        var pie = _pieRepo.GetPieById(id);
        return View(pie);
    }

    public IActionResult Search()
    {
        return View();
    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using PieShop.Models.Repositories;
using PieShop.ViewModels;

namespace PieShop.Controllers;

public class ShoppingCartController : Controller
{

    private readonly IPieRepository _pieRepository;
    private readonly IShoppingCart _shoppingCart;
    
    public ShoppingCartController(IPieRepository pieRepository, IShoppingCart shoppingCart)
    {
        _pieRepository = pieRepository;
        _shoppingCart = shoppingCart;
    }
    public IActionResult Index()
    {
        var items = _shoppingCart.GetShoppingCartItems();
        _shoppingCart.ShoppingCartItems = items;

        var shoppingCartViewModel = new ShoppingCartViewModel(
            _shoppingCart, _shoppingCart.GetShoppingCartTotal());

        return View(shoppingCartViewModel);
    }

    public RedirectToActionResult AddToShppingCart(int pieId)
    {
        var selectedPie = _pieRepository.GetPieById(pieId);
        _shoppingCart.AddToCart(selectedPie);
        return RedirectToAction("Index");
    }
    
    public RedirectToActionResult RemoveFromShoppingCart(int pieId)
    {
        var selectedPie = _pieRepository.GetPieById(pieId);
        _shoppingCart.RemoveFromCart(selectedPie);

        return RedirectToAction("Index");
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselImages" class="carousel slide" data-bs-ride="true">
<div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="2" aria-label="Slide 3"></button>
</div>
<div class="carousel-inner">
    <div class="carousel-item active">
        <img src="~/Images/carousel1.jpg" class="d-block w-100" alt="Carousel image 1">
    </div>
    <div class="carousel-item">
        <img src="~/Images/carousel2.jpg" class="d-block w-100" alt="Carousel image 2">
    </div>
    <div class="carousel-item">
        <img src="~/Images/carousel3.jpg" class="d-block w-100" alt="Carousel image 3">
    </div>
</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="~/lib/jquery/dist/jquery.min.js">
    <link rel="stylesheet" href="~/css/site.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>

<div class="container">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary"
             aria-label="Bethany's Pie Shop navigation header">
            <div class="container-xl">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47" class="d-inline-block align-top mb-2 mt-1"
                         alt="Bethany's Pie Shop Logo">
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                   
                    <vc:category-menu></vc:category-menu>
                    <a asp-controller="Contact" asp-action="Index" class="btn btn-primary">Contact</a>
               
                    <a class="nav-link" asp-controller="Pie" asp-action="Search">
                     <button class="btn btn-warning">Search for Pies</button>
                    </a>
                </div>
                <vc:shopping-cart-summary></vc:shopping-cart-summary>
                <partial name="_LoginPartial"/>
            
            </div>
        </nav>
    </header>
    <main>
        @RenderBody()
        @await RenderSectionAsync("Scripts", required: false)
    </main>
</div>

</body>
</html>

Views/Shared/_PieCard.cshtml
@model Pie

<div class="col">
    <div class="card pie-card">
        <img src="@Model.ImageThumbnailUrl" class="card-img-top" alt="@Model.Name" >
        <div class="card-body pie-button">
            <h4 class="d-grid">
                <a class="btn btn-secondary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShppingCart"
                   asp-route-pieId="@Model.PieId"> + Add to cart</a>
            </h4>

            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a asp-controller="Pie"
                       asp-action="Details"
                       asp-route-id="@Model.PieId"
                       class="pie-link">@Model.Name</a>
                </h2>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("c")
                </h5>
            </div>
        </div>
    </div>
</div>